/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperRouteImport } from './routes/super'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as NovedadesRouteImport } from './routes/novedades'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperIndexRouteImport } from './routes/super.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as SuperTiendasRouteImport } from './routes/super.tiendas'
import { Route as SuperLoginRouteImport } from './routes/super.login'
import { Route as SuperDashboardRouteImport } from './routes/super.dashboard'
import { Route as BioSlugRouteImport } from './routes/bio.$slug'
import { Route as AdminReclamacionesRouteImport } from './routes/admin.reclamaciones'
import { Route as AdminProductosRouteImport } from './routes/admin.productos'
import { Route as AdminPlanRouteImport } from './routes/admin.plan'
import { Route as AdminLinkBioRouteImport } from './routes/admin.link-bio'
import { Route as AdminDisenoRouteImport } from './routes/admin.diseno'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminConfiguracionRouteImport } from './routes/admin.configuracion'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'

const SuperRoute = SuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const NovedadesRoute = NovedadesRouteImport.update({
  id: '/novedades',
  path: '/novedades',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperIndexRoute = SuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperTiendasRoute = SuperTiendasRouteImport.update({
  id: '/tiendas',
  path: '/tiendas',
  getParentRoute: () => SuperRoute,
} as any)
const SuperLoginRoute = SuperLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SuperRoute,
} as any)
const SuperDashboardRoute = SuperDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SuperRoute,
} as any)
const BioSlugRoute = BioSlugRouteImport.update({
  id: '/bio/$slug',
  path: '/bio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReclamacionesRoute = AdminReclamacionesRouteImport.update({
  id: '/reclamaciones',
  path: '/reclamaciones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductosRoute = AdminProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlanRoute = AdminPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinkBioRoute = AdminLinkBioRouteImport.update({
  id: '/link-bio',
  path: '/link-bio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisenoRoute = AdminDisenoRouteImport.update({
  id: '/diseno',
  path: '/diseno',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/novedades': typeof NovedadesRoute
  '/privacidad': typeof PrivacidadRoute
  '/register': typeof RegisterRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diseno': typeof AdminDisenoRoute
  '/admin/link-bio': typeof AdminLinkBioRoute
  '/admin/plan': typeof AdminPlanRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reclamaciones': typeof AdminReclamacionesRoute
  '/bio/$slug': typeof BioSlugRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/login': typeof SuperLoginRoute
  '/super/tiendas': typeof SuperTiendasRoute
  '/t/$slug': typeof TSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/novedades': typeof NovedadesRoute
  '/privacidad': typeof PrivacidadRoute
  '/register': typeof RegisterRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diseno': typeof AdminDisenoRoute
  '/admin/link-bio': typeof AdminLinkBioRoute
  '/admin/plan': typeof AdminPlanRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reclamaciones': typeof AdminReclamacionesRoute
  '/bio/$slug': typeof BioSlugRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/login': typeof SuperLoginRoute
  '/super/tiendas': typeof SuperTiendasRoute
  '/t/$slug': typeof TSlugRoute
  '/admin': typeof AdminIndexRoute
  '/super': typeof SuperIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/novedades': typeof NovedadesRoute
  '/privacidad': typeof PrivacidadRoute
  '/register': typeof RegisterRoute
  '/super': typeof SuperRouteWithChildren
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/diseno': typeof AdminDisenoRoute
  '/admin/link-bio': typeof AdminLinkBioRoute
  '/admin/plan': typeof AdminPlanRoute
  '/admin/productos': typeof AdminProductosRoute
  '/admin/reclamaciones': typeof AdminReclamacionesRoute
  '/bio/$slug': typeof BioSlugRoute
  '/super/dashboard': typeof SuperDashboardRoute
  '/super/login': typeof SuperLoginRoute
  '/super/tiendas': typeof SuperTiendasRoute
  '/t/$slug': typeof TSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/super/': typeof SuperIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/novedades'
    | '/privacidad'
    | '/register'
    | '/super'
    | '/admin/categorias'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/diseno'
    | '/admin/link-bio'
    | '/admin/plan'
    | '/admin/productos'
    | '/admin/reclamaciones'
    | '/bio/$slug'
    | '/super/dashboard'
    | '/super/login'
    | '/super/tiendas'
    | '/t/$slug'
    | '/admin/'
    | '/super/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/novedades'
    | '/privacidad'
    | '/register'
    | '/admin/categorias'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/diseno'
    | '/admin/link-bio'
    | '/admin/plan'
    | '/admin/productos'
    | '/admin/reclamaciones'
    | '/bio/$slug'
    | '/super/dashboard'
    | '/super/login'
    | '/super/tiendas'
    | '/t/$slug'
    | '/admin'
    | '/super'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/novedades'
    | '/privacidad'
    | '/register'
    | '/super'
    | '/admin/categorias'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/diseno'
    | '/admin/link-bio'
    | '/admin/plan'
    | '/admin/productos'
    | '/admin/reclamaciones'
    | '/bio/$slug'
    | '/super/dashboard'
    | '/super/login'
    | '/super/tiendas'
    | '/t/$slug'
    | '/admin/'
    | '/super/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  NovedadesRoute: typeof NovedadesRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RegisterRoute: typeof RegisterRoute
  SuperRoute: typeof SuperRouteWithChildren
  BioSlugRoute: typeof BioSlugRoute
  TSlugRoute: typeof TSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super': {
      id: '/super'
      path: '/super'
      fullPath: '/super'
      preLoaderRoute: typeof SuperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novedades': {
      id: '/novedades'
      path: '/novedades'
      fullPath: '/novedades'
      preLoaderRoute: typeof NovedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/': {
      id: '/super/'
      path: '/'
      fullPath: '/super/'
      preLoaderRoute: typeof SuperIndexRouteImport
      parentRoute: typeof SuperRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super/tiendas': {
      id: '/super/tiendas'
      path: '/tiendas'
      fullPath: '/super/tiendas'
      preLoaderRoute: typeof SuperTiendasRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/login': {
      id: '/super/login'
      path: '/login'
      fullPath: '/super/login'
      preLoaderRoute: typeof SuperLoginRouteImport
      parentRoute: typeof SuperRoute
    }
    '/super/dashboard': {
      id: '/super/dashboard'
      path: '/dashboard'
      fullPath: '/super/dashboard'
      preLoaderRoute: typeof SuperDashboardRouteImport
      parentRoute: typeof SuperRoute
    }
    '/bio/$slug': {
      id: '/bio/$slug'
      path: '/bio/$slug'
      fullPath: '/bio/$slug'
      preLoaderRoute: typeof BioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reclamaciones': {
      id: '/admin/reclamaciones'
      path: '/reclamaciones'
      fullPath: '/admin/reclamaciones'
      preLoaderRoute: typeof AdminReclamacionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/productos': {
      id: '/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AdminProductosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plan': {
      id: '/admin/plan'
      path: '/plan'
      fullPath: '/admin/plan'
      preLoaderRoute: typeof AdminPlanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/link-bio': {
      id: '/admin/link-bio'
      path: '/link-bio'
      fullPath: '/admin/link-bio'
      preLoaderRoute: typeof AdminLinkBioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/diseno': {
      id: '/admin/diseno'
      path: '/diseno'
      fullPath: '/admin/diseno'
      preLoaderRoute: typeof AdminDisenoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDisenoRoute: typeof AdminDisenoRoute
  AdminLinkBioRoute: typeof AdminLinkBioRoute
  AdminPlanRoute: typeof AdminPlanRoute
  AdminProductosRoute: typeof AdminProductosRoute
  AdminReclamacionesRoute: typeof AdminReclamacionesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDisenoRoute: AdminDisenoRoute,
  AdminLinkBioRoute: AdminLinkBioRoute,
  AdminPlanRoute: AdminPlanRoute,
  AdminProductosRoute: AdminProductosRoute,
  AdminReclamacionesRoute: AdminReclamacionesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SuperRouteChildren {
  SuperDashboardRoute: typeof SuperDashboardRoute
  SuperLoginRoute: typeof SuperLoginRoute
  SuperTiendasRoute: typeof SuperTiendasRoute
  SuperIndexRoute: typeof SuperIndexRoute
}

const SuperRouteChildren: SuperRouteChildren = {
  SuperDashboardRoute: SuperDashboardRoute,
  SuperLoginRoute: SuperLoginRoute,
  SuperTiendasRoute: SuperTiendasRoute,
  SuperIndexRoute: SuperIndexRoute,
}

const SuperRouteWithChildren = SuperRoute._addFileChildren(SuperRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  NovedadesRoute: NovedadesRoute,
  PrivacidadRoute: PrivacidadRoute,
  RegisterRoute: RegisterRoute,
  SuperRoute: SuperRouteWithChildren,
  BioSlugRoute: BioSlugRoute,
  TSlugRoute: TSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
