-- DIZI Production Database Schema Dump
-- Date: 2026-09-25
-- Database: zkqzdwxjthjdjchimmds.supabase.co
-- Generated by Antigravity Phase 0 Backup Tool

SET statement_timeout = 0;
SET lock_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;
SET row_security = off;

CREATE SCHEMA IF NOT EXISTS public;

-- 0. Extensions
CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA extensions;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA extensions;

-- 1. Tables
-- Table: public.categories
CREATE TABLE IF NOT EXISTS public.categories (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  store_id text NOT NULL,
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: public.invites
CREATE TABLE IF NOT EXISTS public.invites (
  token text NOT NULL,
  plan text DEFAULT 'semilla'::text NOT NULL,
  used boolean DEFAULT false NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  expires_at timestamp with time zone DEFAULT (timezone('utc'::text, now()) + '30 days'::interval) NOT NULL,
  duration_months integer DEFAULT 1 NOT NULL,
  notes text,
  custom_price numeric,
  duration_value integer DEFAULT 1 NOT NULL,
  duration_unit text DEFAULT 'months'::text NOT NULL
);

-- Table: public.products
CREATE TABLE IF NOT EXISTS public.products (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  store_id text NOT NULL,
  category_id text,
  name text NOT NULL,
  price numeric DEFAULT 0,
  original_price numeric,
  image text,
  description text,
  is_on_sale boolean DEFAULT false,
  visible boolean DEFAULT true,
  is_sample boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  sort_order integer DEFAULT 0 NOT NULL,
  tags text[] DEFAULT '{}'::text[],
  variations jsonb DEFAULT '[]'::jsonb
);

-- Table: public.reclamaciones
CREATE TABLE IF NOT EXISTS public.reclamaciones (
  id uuid DEFAULT gen_random_uuid() NOT NULL,
  tenant_id text NOT NULL,
  numero_correlativo integer NOT NULL,
  fecha timestamp with time zone DEFAULT now() NOT NULL,
  estado text DEFAULT 'pendiente'::text NOT NULL,
  fecha_respuesta timestamp with time zone,
  respuesta_proveedor text,
  empresa_nombre text NOT NULL,
  empresa_ruc text,
  empresa_direccion text,
  empresa_url text,
  consumidor_nombre text NOT NULL,
  consumidor_tipo_doc text DEFAULT 'DNI'::text NOT NULL,
  consumidor_num_doc text NOT NULL,
  consumidor_domicilio text,
  consumidor_telefono text,
  consumidor_email text,
  es_menor_edad boolean DEFAULT false NOT NULL,
  tutor_nombre text,
  tutor_num_doc text,
  bien_descripcion text,
  bien_monto numeric,
  tipo text NOT NULL,
  descripcion text NOT NULL,
  pedido_consumidor text
);

-- Table: public.stores
CREATE TABLE IF NOT EXISTS public.stores (
  id text DEFAULT (gen_random_uuid())::text NOT NULL,
  slug text NOT NULL,
  name text NOT NULL,
  phone text,
  country_code text DEFAULT '51'::text,
  logo text,
  plan text DEFAULT 'semilla'::text,
  model text DEFAULT 'minimalista'::text,
  brand_color text,
  active boolean DEFAULT true,
  is_published boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  bg_color text,
  owner_id uuid,
  whatsapp_clicks integer DEFAULT 0,
  niche text,
  banner_image text,
  banner_title text,
  price_filter_enabled boolean DEFAULT false NOT NULL,
  plan_expires_at timestamp with time zone,
  subscription_status text DEFAULT 'trial'::text NOT NULL,
  cancelled_at timestamp with time zone,
  cancel_reason text,
  plan_duration_months integer DEFAULT 1,
  libro_reclamaciones_activo boolean DEFAULT false NOT NULL,
  empresa_ruc text,
  empresa_razon_social text,
  empresa_direccion text,
  bio_description text,
  location_lat double precision,
  location_lng double precision,
  location_address text,
  quick_links jsonb DEFAULT '[]'::jsonb,
  bio_links_enabled boolean DEFAULT false,
  bio_logo text,
  bio_banner text,
  bio_theme text,
  bio_button_style text,
  bio_button_color text,
  bio_button_text_color text,
  bio_bg_image text,
  bio_bg_color text,
  views integer DEFAULT 0,
  bio_typography text DEFAULT 'sans'::text,
  custom_price numeric,
  banner_style text DEFAULT 'direct'::text,
  catalog_typography text DEFAULT 'sans'::text,
  card_style text DEFAULT 'standard'::text,
  text_color text,
  banner_tagline text,
  banner_bottom_tag text,
  show_dizi_branding boolean DEFAULT true,
  onboarding_completed boolean DEFAULT false,
  bio_show_catalog_button boolean,
  promo_bar_enabled boolean DEFAULT false,
  promo_bar_text text DEFAULT ''::text,
  promo_bar_action_type text DEFAULT 'none'::text,
  promo_bar_action_value text DEFAULT ''::text,
  promo_bar_bg_color text,
  promo_bar_text_color text,
  promo_bar_is_marquee boolean DEFAULT false,
  show_map boolean,
  referred_by text,
  referral_rewarded boolean,
  egress_bytes bigint DEFAULT 0,
  card_bg text,
  accent_color text,
  border_radius text,
  img_shape text,
  is_dark boolean,
  legacy_model text,
  legacy_niche text,
  banners text[] DEFAULT '{}'::text[],
  updated_at timestamp with time zone DEFAULT now()
);

-- 2. Constraints
ALTER TABLE public.categories DROP CONSTRAINT IF EXISTS categories_pkey;
ALTER TABLE public.categories ADD CONSTRAINT categories_pkey PRIMARY KEY (id);
ALTER TABLE public.invites DROP CONSTRAINT IF EXISTS invites_pkey;
ALTER TABLE public.invites ADD CONSTRAINT invites_pkey PRIMARY KEY (token);
ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_pkey;
ALTER TABLE public.products ADD CONSTRAINT products_pkey PRIMARY KEY (id);
ALTER TABLE public.reclamaciones DROP CONSTRAINT IF EXISTS reclamaciones_pkey;
ALTER TABLE public.reclamaciones ADD CONSTRAINT reclamaciones_pkey PRIMARY KEY (id);
ALTER TABLE public.stores DROP CONSTRAINT IF EXISTS stores_pkey;
ALTER TABLE public.stores ADD CONSTRAINT stores_pkey PRIMARY KEY (id);
ALTER TABLE public.reclamaciones DROP CONSTRAINT IF EXISTS reclamaciones_tenant_id_numero_correlativo_key;
ALTER TABLE public.reclamaciones ADD CONSTRAINT reclamaciones_tenant_id_numero_correlativo_key UNIQUE (tenant_id, numero_correlativo);
ALTER TABLE public.stores DROP CONSTRAINT IF EXISTS stores_slug_key;
ALTER TABLE public.stores ADD CONSTRAINT stores_slug_key UNIQUE (slug);
ALTER TABLE public.stores DROP CONSTRAINT IF EXISTS chk_subscription_status;
ALTER TABLE public.stores ADD CONSTRAINT chk_subscription_status CHECK ((subscription_status = ANY (ARRAY['active'::text, 'expired'::text, 'cancelled'::text, 'trial'::text])));
ALTER TABLE public.invites DROP CONSTRAINT IF EXISTS invites_duration_unit_check;
ALTER TABLE public.invites ADD CONSTRAINT invites_duration_unit_check CHECK ((duration_unit = ANY (ARRAY['days'::text, 'months'::text])));
ALTER TABLE public.reclamaciones DROP CONSTRAINT IF EXISTS reclamaciones_consumidor_tipo_doc_check;
ALTER TABLE public.reclamaciones ADD CONSTRAINT reclamaciones_consumidor_tipo_doc_check CHECK ((consumidor_tipo_doc = ANY (ARRAY['DNI'::text, 'CE'::text, 'Pasaporte'::text, 'RUC'::text])));
ALTER TABLE public.reclamaciones DROP CONSTRAINT IF EXISTS reclamaciones_estado_check;
ALTER TABLE public.reclamaciones ADD CONSTRAINT reclamaciones_estado_check CHECK ((estado = ANY (ARRAY['pendiente'::text, 'en_revision'::text, 'resuelto'::text])));
ALTER TABLE public.reclamaciones DROP CONSTRAINT IF EXISTS reclamaciones_tipo_check;
ALTER TABLE public.reclamaciones ADD CONSTRAINT reclamaciones_tipo_check CHECK ((tipo = ANY (ARRAY['queja'::text, 'reclamo'::text])));
ALTER TABLE public.categories DROP CONSTRAINT IF EXISTS categories_store_id_fkey;
ALTER TABLE public.categories ADD CONSTRAINT categories_store_id_fkey FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE;
ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_category_id_fkey;
ALTER TABLE public.products ADD CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;
ALTER TABLE public.products DROP CONSTRAINT IF EXISTS products_store_id_fkey;
ALTER TABLE public.products ADD CONSTRAINT products_store_id_fkey FOREIGN KEY (store_id) REFERENCES stores(id) ON DELETE CASCADE;
ALTER TABLE public.reclamaciones DROP CONSTRAINT IF EXISTS reclamaciones_tenant_id_fkey;
ALTER TABLE public.reclamaciones ADD CONSTRAINT reclamaciones_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES stores(id) ON DELETE CASCADE;

-- 3. RLS and Policies
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow_All_categories" ON public.categories;
CREATE POLICY "Allow_All_categories" ON public.categories FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "categories_owner_all" ON public.categories;
CREATE POLICY "categories_owner_all" ON public.categories FOR ALL TO authenticated USING ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = categories.store_id) AND (stores.owner_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = categories.store_id) AND (stores.owner_id = auth.uid())))));
DROP POLICY IF EXISTS "categories_public_select" ON public.categories;
CREATE POLICY "categories_public_select" ON public.categories FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = categories.store_id) AND (((stores.active = true) AND (stores.is_published = true)) OR (stores.owner_id = auth.uid()))))));
DROP POLICY IF EXISTS "categories_superadmin_all" ON public.categories;
CREATE POLICY "categories_superadmin_all" ON public.categories FOR ALL TO authenticated USING ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text)) WITH CHECK ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text));

ALTER TABLE public.invites ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow_All_invites" ON public.invites;
CREATE POLICY "Allow_All_invites" ON public.invites FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Permitir actualización a super admins" ON public.invites;
CREATE POLICY "Permitir actualización a super admins" ON public.invites FOR UPDATE TO public USING (((auth.role() = 'service_role'::text) OR (COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text)));
DROP POLICY IF EXISTS "Permitir eliminación a super admins" ON public.invites;
CREATE POLICY "Permitir eliminación a super admins" ON public.invites FOR DELETE TO public USING (((auth.role() = 'service_role'::text) OR (COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text)));
DROP POLICY IF EXISTS "Permitir inserción a super admins" ON public.invites;
CREATE POLICY "Permitir inserción a super admins" ON public.invites FOR INSERT TO public WITH CHECK (((auth.role() = 'service_role'::text) OR (COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text)));
DROP POLICY IF EXISTS "Permitir lectura a super admins" ON public.invites;
CREATE POLICY "Permitir lectura a super admins" ON public.invites FOR SELECT TO authenticated USING ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text));

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow_All_products" ON public.products;
CREATE POLICY "Allow_All_products" ON public.products FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "products_owner_all" ON public.products;
CREATE POLICY "products_owner_all" ON public.products FOR ALL TO authenticated USING ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = products.store_id) AND (stores.owner_id = auth.uid()))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = products.store_id) AND (stores.owner_id = auth.uid())))));
DROP POLICY IF EXISTS "products_public_select" ON public.products;
CREATE POLICY "products_public_select" ON public.products FOR SELECT TO public USING ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = products.store_id) AND (((stores.active = true) AND (stores.is_published = true)) OR (stores.owner_id = auth.uid()))))));
DROP POLICY IF EXISTS "products_superadmin_all" ON public.products;
CREATE POLICY "products_superadmin_all" ON public.products FOR ALL TO authenticated USING ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text)) WITH CHECK ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text));

ALTER TABLE public.reclamaciones ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reclamaciones_owner_all" ON public.reclamaciones;
CREATE POLICY "reclamaciones_owner_all" ON public.reclamaciones FOR SELECT TO authenticated USING ((EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = reclamaciones.tenant_id) AND (stores.owner_id = auth.uid())))));
DROP POLICY IF EXISTS "reclamaciones_owner_delete" ON public.reclamaciones;
CREATE POLICY "reclamaciones_owner_delete" ON public.reclamaciones FOR DELETE TO authenticated USING (((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text) OR (EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = reclamaciones.tenant_id) AND (stores.owner_id = auth.uid()))))));
DROP POLICY IF EXISTS "reclamaciones_owner_select" ON public.reclamaciones;
CREATE POLICY "reclamaciones_owner_select" ON public.reclamaciones FOR SELECT TO authenticated USING (((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text) OR (EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = reclamaciones.tenant_id) AND (stores.owner_id = auth.uid()))))));
DROP POLICY IF EXISTS "reclamaciones_owner_update" ON public.reclamaciones;
CREATE POLICY "reclamaciones_owner_update" ON public.reclamaciones FOR UPDATE TO authenticated USING (((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text) OR (EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = reclamaciones.tenant_id) AND (stores.owner_id = auth.uid())))))) WITH CHECK (((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text) OR (EXISTS ( SELECT 1
   FROM stores
  WHERE ((stores.id = reclamaciones.tenant_id) AND (stores.owner_id = auth.uid()))))));
DROP POLICY IF EXISTS "reclamaciones_public_insert" ON public.reclamaciones;
CREATE POLICY "reclamaciones_public_insert" ON public.reclamaciones FOR INSERT TO public WITH CHECK (true);

ALTER TABLE public.stores ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow_All_stores" ON public.stores;
CREATE POLICY "Allow_All_stores" ON public.stores FOR ALL TO public USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "stores_owner_delete" ON public.stores;
CREATE POLICY "stores_owner_delete" ON public.stores FOR DELETE TO authenticated USING ((auth.uid() = owner_id));
DROP POLICY IF EXISTS "stores_owner_insert" ON public.stores;
CREATE POLICY "stores_owner_insert" ON public.stores FOR INSERT TO authenticated WITH CHECK ((auth.uid() = owner_id));
DROP POLICY IF EXISTS "stores_owner_select" ON public.stores;
CREATE POLICY "stores_owner_select" ON public.stores FOR SELECT TO authenticated USING ((auth.uid() = owner_id));
DROP POLICY IF EXISTS "stores_owner_update" ON public.stores;
CREATE POLICY "stores_owner_update" ON public.stores FOR UPDATE TO authenticated USING ((auth.uid() = owner_id)) WITH CHECK ((auth.uid() = owner_id));
DROP POLICY IF EXISTS "stores_public_select" ON public.stores;
CREATE POLICY "stores_public_select" ON public.stores FOR SELECT TO public USING (((active = true) AND (is_published = true)));
DROP POLICY IF EXISTS "stores_superadmin_delete" ON public.stores;
CREATE POLICY "stores_superadmin_delete" ON public.stores FOR DELETE TO authenticated USING ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text));
DROP POLICY IF EXISTS "stores_superadmin_insert" ON public.stores;
CREATE POLICY "stores_superadmin_insert" ON public.stores FOR INSERT TO authenticated WITH CHECK ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text));
DROP POLICY IF EXISTS "stores_superadmin_select" ON public.stores;
CREATE POLICY "stores_superadmin_select" ON public.stores FOR SELECT TO authenticated USING ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text));
DROP POLICY IF EXISTS "stores_superadmin_update" ON public.stores;
CREATE POLICY "stores_superadmin_update" ON public.stores FOR UPDATE TO authenticated USING ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text)) WITH CHECK ((COALESCE(((auth.jwt() -> 'app_metadata'::text) ->> 'role'::text), ''::text) = 'super_admin'::text));

-- Indexes
CREATE INDEX IF NOT EXISTS idx_products_store_sort ON public.products USING btree (store_id, sort_order, created_at DESC);
CREATE INDEX IF NOT EXISTS reclamaciones_estado_idx ON public.reclamaciones USING btree (estado);
CREATE INDEX IF NOT EXISTS reclamaciones_fecha_idx ON public.reclamaciones USING btree (fecha DESC);
CREATE INDEX IF NOT EXISTS reclamaciones_tenant_id_idx ON public.reclamaciones USING btree (tenant_id);
CREATE INDEX IF NOT EXISTS idx_stores_plan_expires_at ON public.stores USING btree (plan_expires_at) WHERE (subscription_status = 'active'::text);
CREATE INDEX IF NOT EXISTS idx_stores_subscription_status ON public.stores USING btree (subscription_status);

-- Functions
CREATE OR REPLACE FUNCTION public.activate_subscription(p_store_id text, p_plan text, p_duration_months integer DEFAULT 1, p_custom_price numeric DEFAULT NULL::numeric, p_keep_expiration boolean DEFAULT false, p_manual_expiration timestamp with time zone DEFAULT NULL::timestamp with time zone)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_expires_at TIMESTAMPTZ;
BEGIN
  -- Verificar autorización de Superadmin o service_role
  IF auth.role() != 'service_role' AND COALESCE((auth.jwt()->'app_metadata'->>'role'), '') != 'super_admin' THEN
    RAISE EXCEPTION 'No autorizado. Solo super administradores pueden realizar esta acción.';
  END IF;

  -- Si el plan es semilla (gratis), no se establece expiración
  IF p_plan = 'semilla' THEN
    UPDATE public.stores
    SET
      plan                 = p_plan,
      plan_expires_at      = NULL,
      subscription_status  = 'trial',
      plan_duration_months = NULL,
      custom_price         = NULL
    WHERE id = p_store_id;
  ELSE
    -- Determinar la nueva fecha de vencimiento
    IF p_manual_expiration IS NOT NULL THEN
      -- Se establece una fecha manual explícita
      UPDATE public.stores
      SET
        plan                 = p_plan,
        plan_expires_at      = p_manual_expiration,
        subscription_status  = 'active',
        custom_price         = p_custom_price,
        cancelled_at         = NULL,
        cancel_reason        = NULL
      WHERE id = p_store_id;
    ELSIF p_keep_expiration THEN
      -- Se mantiene la fecha de vencimiento actual de la tienda
      UPDATE public.stores
      SET
        plan                 = p_plan,
        subscription_status  = 'active',
        custom_price         = p_custom_price,
        cancelled_at         = NULL,
        cancel_reason        = NULL
      WHERE id = p_store_id;
    ELSE
      -- Se extiende sumando meses desde NOW()
      v_expires_at := NOW() + (p_duration_months || ' months')::INTERVAL;
      UPDATE public.stores
      SET
        plan                 = p_plan,
        plan_expires_at      = v_expires_at,
        subscription_status  = 'active',
        plan_duration_months = p_duration_months,
        custom_price         = p_custom_price,
        cancelled_at         = NULL,
        cancel_reason        = NULL
      WHERE id = p_store_id;
    END IF;
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.activate_subscription(p_store_id text, p_plan text, p_duration_months integer DEFAULT 1, p_custom_price numeric DEFAULT NULL::numeric)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_expires_at TIMESTAMPTZ;
  v_referred_price NUMERIC;
BEGIN
  -- Verificar autorización
  IF auth.role() != 'service_role' AND COALESCE((auth.jwt()->'app_metadata'->>'role'), '') != 'super_admin' THEN
    RAISE EXCEPTION 'No autorizado. Solo super administradores pueden realizar esta acción.';
  END IF;

  -- Si el plan es semilla (gratis), no se establece expiración
  IF p_plan = 'semilla' THEN
    UPDATE public.stores
    SET
      plan                 = p_plan,
      plan_expires_at      = NULL,
      subscription_status  = 'trial',
      plan_duration_months = NULL,
      custom_price         = NULL
    WHERE id = p_store_id;
  ELSE
    v_expires_at := NOW() + (p_duration_months || ' months')::INTERVAL;
    UPDATE public.stores
    SET
      plan                 = p_plan,
      plan_expires_at      = v_expires_at,
      subscription_status  = 'active',
      plan_duration_months = p_duration_months,
      custom_price         = p_custom_price,
      cancelled_at         = NULL,
      cancel_reason        = NULL
    WHERE id = p_store_id;

    -- AUTOMATIZACIÓN DE REFERIDOS:
    -- Calcular precio efectivo pagado por el referido
    v_referred_price := COALESCE(p_custom_price, public.get_plan_price(p_plan));
    
    -- Procesar la recompensa de tiempo si el plan adquirido es de pago
    IF v_referred_price > 0 THEN
      PERFORM public.process_referral_reward(p_store_id, p_plan, v_referred_price);
    END IF;
  END IF;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.activate_subscription_with_invite(p_store_id text, p_invite_token text)
 RETURNS TABLE(plan text, duration_value integer, duration_unit text, custom_price numeric)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_invite RECORD;
  v_expires_at TIMESTAMPTZ;
  v_subscription_status TEXT;
  v_plan_duration_months INT;
BEGIN
  -- 1. Buscar y bloquear la fila del invite para evitar condiciones de carrera
  SELECT * INTO v_invite
  FROM public.invites
  WHERE token = p_invite_token AND used = false AND expires_at > NOW()
  FOR UPDATE;

  IF v_invite IS NULL THEN
    RAISE EXCEPTION 'El enlace de invitación no es válido o ya fue utilizado.';
  END IF;

  -- 2. Marcar el invite como usado
  UPDATE public.invites
  SET used = true
  WHERE token = p_invite_token;

  -- 3. Activar la suscripción de la tienda
  IF v_invite.plan = 'semilla' THEN
    UPDATE public.stores
    SET
      plan                 = v_invite.plan,
      plan_expires_at      = NULL,
      subscription_status  = 'trial',
      plan_duration_months = NULL,
      custom_price         = NULL
    WHERE id = p_store_id;
  ELSE
    -- Calcular expiración y estado según la unidad
    IF v_invite.duration_unit = 'days' THEN
      v_expires_at := NOW() + (v_invite.duration_value || ' days')::INTERVAL;
      v_subscription_status := 'trial';
      v_plan_duration_months := 0;
    ELSE
      v_expires_at := NOW() + (v_invite.duration_value || ' months')::INTERVAL;
      v_subscription_status := 'active';
      v_plan_duration_months := v_invite.duration_value;
    END IF;

    UPDATE public.stores
    SET
      plan                 = v_invite.plan,
      plan_expires_at      = v_expires_at,
      subscription_status  = v_subscription_status,
      plan_duration_months = v_plan_duration_months,
      custom_price         = v_invite.custom_price,
      cancelled_at         = NULL,
      cancel_reason        = NULL
    WHERE id = p_store_id;
  END IF;

  RETURN QUERY 
  SELECT 
    v_invite.plan::TEXT, 
    v_invite.duration_value::INT, 
    v_invite.duration_unit::TEXT, 
    v_invite.custom_price::NUMERIC;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.cancel_subscription(p_store_id text, p_reason text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Verificar que el ejecutor sea service_role o un usuario autenticado con rol super_admin en app_metadata
  IF auth.role() != 'service_role' AND COALESCE((auth.jwt()->'app_metadata'->>'role'), '') != 'super_admin' THEN
    RAISE EXCEPTION 'No autorizado. Solo super administradores pueden realizar esta acción.';
  END IF;

  UPDATE public.stores
  SET
    plan                = 'semilla',
    subscription_status = 'cancelled',
    cancelled_at        = NOW(),
    cancel_reason       = p_reason,
    plan_expires_at     = NOW()  -- vence inmediatamente
  WHERE id = p_store_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.check_invite(p_token text)
 RETURNS TABLE(plan text, expires_at timestamp with time zone, duration_months integer, duration_value integer, duration_unit text, custom_price numeric)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  RETURN QUERY
  SELECT 
    i.plan::TEXT, 
    i.expires_at, 
    i.duration_months::INT, 
    i.duration_value::INT, 
    i.duration_unit::TEXT, 
    i.custom_price::NUMERIC
  FROM public.invites i
  WHERE i.token = p_token 
    AND i.used = false 
    AND i.expires_at > NOW();
END;
$function$
;

CREATE OR REPLACE FUNCTION public.degrade_expired_plans()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_count INT;
BEGIN
  UPDATE stores
  SET
    plan                = 'semilla',
    subscription_status = 'expired'
  WHERE
    subscription_status = 'active'
    AND plan_expires_at IS NOT NULL
    AND plan_expires_at < NOW();

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.extend_subscription(p_store_id text, p_months_to_add integer DEFAULT 1)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_current_expires TIMESTAMPTZ;
BEGIN
  -- Verificar que el ejecutor sea service_role o un usuario autenticado con rol super_admin en app_metadata
  IF auth.role() != 'service_role' AND COALESCE((auth.jwt()->'app_metadata'->>'role'), '') != 'super_admin' THEN
    RAISE EXCEPTION 'No autorizado. Solo super administradores pueden realizar esta acción.';
  END IF;

  SELECT plan_expires_at INTO v_current_expires FROM public.stores WHERE id = p_store_id;

  -- Si ya expiró, extiende desde ahora; si no, extiende desde la fecha actual
  UPDATE public.stores
  SET
    plan_expires_at     = GREATEST(v_current_expires, NOW()) + (p_months_to_add || ' months')::INTERVAL,
    subscription_status = 'active',
    cancelled_at        = NULL,
    cancel_reason       = NULL
  WHERE id = p_store_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_public_store(store_slug text, page_limit integer DEFAULT 36, page_offset integer DEFAULT 0)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  store_row record;
  store_plan text;
  days_expired int;
  effective_limit int;
  effective_model text;
  effective_banner text;
  total_prod_count int;
  actual_limit int;
  result jsonb;
BEGIN
  SELECT * INTO store_row FROM stores WHERE slug = store_slug AND active = true LIMIT 1;
  IF store_row IS NULL THEN
    RETURN NULL;
  END IF;

  IF store_row.plan_expires_at IS NOT NULL AND store_row.plan_expires_at < now() THEN
    days_expired := date_part('day', now() - store_row.plan_expires_at)::int;
  ELSE
    days_expired := -1;
  END IF;

  IF store_row.plan = 'semilla' THEN
    store_plan := 'semilla';
  ELSIF days_expired > 3 THEN
    store_plan := 'semilla';
  ELSE
    store_plan := store_row.plan;
  END IF;

  IF store_plan = 'semilla' THEN
    effective_limit := 20;
  ELSIF store_plan = 'emprendedor' THEN
    effective_limit := 100;
  ELSIF store_plan = 'pro' THEN
    effective_limit := 300;
  ELSIF store_plan = 'ilimitado' THEN
    effective_limit := 1000;
  ELSE
    effective_limit := 1000;
  END IF;

  effective_model := COALESCE(store_row.model, 'minimalista');

  -- Combinar las imágenes de los banners si existe el arreglo banners
  IF store_row.banners IS NOT NULL AND array_length(store_row.banners, 1) > 0 THEN
    effective_banner := array_to_string(store_row.banners, '|||');
  ELSE
    effective_banner := store_row.banner_image;
  END IF;

  -- Contar el total de productos visibles para este store (hasta el límite de su plan)
  SELECT LEAST(count(*), effective_limit) INTO total_prod_count
  FROM products
  WHERE store_id = store_row.id AND visible = true;

  -- Calcular el límite real para este lote
  actual_limit := LEAST(COALESCE(page_limit, 36), effective_limit);

  SELECT jsonb_build_object(
    'id', store_row.id,
    'slug', store_row.slug,
    'name', store_row.name,
    'phone', store_row.phone,
    'country_code', store_row.country_code,
    'logo', store_row.logo,
    'brand_color', store_row.brand_color,
    'bg_color', store_row.bg_color,
    'text_color', store_row.text_color,
    'card_bg', store_row.card_bg,
    'accent_color', store_row.accent_color,
    'border_radius', store_row.border_radius,
    'img_shape', store_row.img_shape,
    'is_dark', store_row.is_dark,
    'banner_image', effective_banner,
    'banner_title', store_row.banner_title,
    'banner_style', COALESCE(store_row.banner_style, 'direct'),
    'niche', COALESCE(store_row.niche, 'general'),
    'catalog_typography', COALESCE(store_row.catalog_typography, 'sans'),
    'card_style', COALESCE(store_row.card_style, 'standard'),
    'plan', store_plan,
    'model', effective_model,
    'active', store_row.active,
    'is_published', store_row.is_published,
    'created_at', store_row.created_at,
    'whatsapp_clicks', COALESCE(store_row.whatsapp_clicks, 0),
    'views', COALESCE(store_row.views, 0),
    'price_filter_enabled', store_row.price_filter_enabled,
    'libro_reclamaciones_activo', store_row.libro_reclamaciones_activo,
    'empresa_ruc', store_row.empresa_ruc,
    'empresa_razon_social', store_row.empresa_razon_social,
    'empresa_direccion', store_row.empresa_direccion,
    'total_products_count', COALESCE(total_prod_count, 0)
  ) || jsonb_build_object(
    'plan_expires_at', store_row.plan_expires_at,
    'subscription_status', store_row.subscription_status,
    'cancelled_at', store_row.cancelled_at,
    'cancel_reason', store_row.cancel_reason,
    'plan_duration_months', store_row.plan_duration_months,
    'bio_description', store_row.bio_description,
    'bio_links_enabled', COALESCE(store_row.bio_links_enabled, false),
    'bio_banner', store_row.bio_banner,
    'bio_logo', store_row.bio_logo,
    'bio_theme', store_row.bio_theme,
    'bio_typography', store_row.bio_typography,
    'bio_show_catalog_button', store_row.bio_show_catalog_button,
    'bio_button_style', store_row.bio_button_style,
    'bio_button_color', store_row.bio_button_color,
    'bio_button_text_color', store_row.bio_button_text_color,
    'bio_bg_image', store_row.bio_bg_image,
    'bio_bg_color', store_row.bio_bg_color,
    'quick_links', (
      CASE WHEN store_plan = 'semilla' THEN
          COALESCE((SELECT jsonb_agg(value) FROM (SELECT value FROM jsonb_array_elements(COALESCE(store_row.quick_links, '[]'::jsonb)) LIMIT 3) t), '[]'::jsonb)
      ELSE
          COALESCE(store_row.quick_links, '[]'::jsonb)
      END
    ),
    'location_lat', store_row.location_lat,
    'location_lng', store_row.location_lng,
    'location_address', store_row.location_address,
    'banner_tagline', store_row.banner_tagline,
    'banner_bottom_tag', store_row.banner_bottom_tag,
    'show_dizi_branding', store_row.show_dizi_branding,
    'promo_bar_enabled', store_row.promo_bar_enabled,
    'promo_bar_text', store_row.promo_bar_text,
    'promo_bar_action_type', store_row.promo_bar_action_type,
    'promo_bar_action_value', store_row.promo_bar_action_value,
    'promo_bar_bg_color', store_row.promo_bar_bg_color,
    'promo_bar_text_color', store_row.promo_bar_text_color,
    'promo_bar_is_marquee', store_row.promo_bar_is_marquee,
    'categories', (
      SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'id', c.id,
        'name', c.name,
        'product_count', (
          SELECT count(*)::int FROM products p 
          WHERE p.store_id = store_row.id AND p.category_id = c.id AND p.visible = true
        )
      )), '[]'::jsonb)
      FROM categories c
      WHERE c.store_id = store_row.id
    ),
    'products', (
      SELECT COALESCE(jsonb_agg(jsonb_build_object(
        'id', id,
        'name', name,
        'price', price,
        'category_id', category_id,
        'image', image,
        'description', description,
        'is_on_sale', is_on_sale,
        'original_price', original_price,
        'visible', visible,
        'is_sample', is_sample,
        'sort_order', sort_order,
        'variations', COALESCE(variations, '[]'::jsonb),
        'created_at', created_at
      )), '[]'::jsonb)
      FROM (
        SELECT * FROM products
        WHERE store_id = store_row.id AND visible = true
        ORDER BY sort_order ASC NULLS LAST, created_at DESC
        LIMIT actual_limit
        OFFSET COALESCE(page_offset, 0)
      ) p
    )
  ) INTO result;

  RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.get_public_store_products(p_store_slug text, p_page_offset integer DEFAULT 0, p_page_limit integer DEFAULT 24, p_category_id text DEFAULT NULL::text, p_search_query text DEFAULT NULL::text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_store_row record;
  v_effective_limit int;
  result jsonb;
BEGIN
  SELECT id, plan, plan_expires_at INTO v_store_row FROM stores WHERE slug = p_store_slug AND active = true LIMIT 1;
  IF v_store_row IS NULL THEN
    RETURN '[]'::jsonb;
  END IF;

  IF v_store_row.plan = 'semilla' THEN
    v_effective_limit := 20;
  ELSIF v_store_row.plan = 'emprendedor' THEN
    v_effective_limit := 100;
  ELSIF v_store_row.plan = 'pro' THEN
    v_effective_limit := 300;
  ELSE
    v_effective_limit := 1000;
  END IF;

  SELECT COALESCE(jsonb_agg(jsonb_build_object(
    'id', p.id,
    'name', p.name,
    'price', p.price,
    'category_id', p.category_id,
    'image', p.image,
    'description', p.description,
    'is_on_sale', p.is_on_sale,
    'original_price', p.original_price,
    'visible', p.visible,
    'is_sample', p.is_sample,
    'sort_order', p.sort_order,
    'variations', COALESCE(p.variations, '[]'::jsonb),
    'created_at', p.created_at
  )), '[]'::jsonb) INTO result
  FROM (
    SELECT * FROM products
    WHERE store_id = v_store_row.id 
      AND visible = true
      AND (p_category_id IS NULL OR p_category_id = '' OR p_category_id = 'all' OR products.category_id = p_category_id)
      AND (
        p_search_query IS NULL 
        OR p_search_query = '' 
        OR products.name ILIKE '%' || p_search_query || '%'
        OR COALESCE(products.description, '') ILIKE '%' || p_search_query || '%'
      )
    ORDER BY sort_order ASC NULLS LAST, created_at DESC
    LIMIT LEAST(COALESCE(p_page_limit, 24), v_effective_limit)
    OFFSET COALESCE(p_page_offset, 0)
  ) p;

  RETURN result;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_store_touch_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF TG_TABLE_NAME = 'stores' THEN
    NEW.updated_at = NOW();
    RETURN NEW;
  ELSIF TG_TABLE_NAME = 'products' THEN
    IF TG_OP = 'DELETE' THEN
      UPDATE public.stores SET updated_at = NOW() WHERE id = OLD.store_id;
      RETURN OLD;
    ELSE
      UPDATE public.stores SET updated_at = NOW() WHERE id = NEW.store_id;
      RETURN NEW;
    END IF;
  END IF;
  RETURN NULL;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_user_sync_role()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  IF TG_OP = 'INSERT' THEN
    -- Si se intenta registrar con rol 'super_admin' en user_metadata, forzar a 'store_owner'
    IF COALESCE(NEW.raw_user_meta_data->>'role', '') = 'super_admin' THEN
      NEW.raw_user_meta_data := NEW.raw_user_meta_data || jsonb_build_object('role', 'store_owner');
    END IF;
    NEW.raw_app_meta_data := NEW.raw_app_meta_data || jsonb_build_object('role', COALESCE(NEW.raw_user_meta_data->>'role', 'store_owner'));
    
  ELSIF TG_OP = 'UPDATE' THEN
    -- Bloquear auto-promoción si un cliente intenta cambiar su propio user_metadata a 'super_admin'
    IF NEW.raw_user_meta_data->>'role' = 'super_admin' 
       AND (OLD.raw_user_meta_data->>'role' IS NULL OR OLD.raw_user_meta_data->>'role' != 'super_admin') 
       AND COALESCE(OLD.raw_app_meta_data->>'role', '') != 'super_admin' 
       AND COALESCE(NEW.raw_app_meta_data->>'role', '') != 'super_admin' THEN
      NEW.raw_user_meta_data := NEW.raw_user_meta_data || jsonb_build_object('role', 'store_owner');
    END IF;
    
    -- Sincronizar el app_metadata con el user_metadata si el usuario no es super_admin
    -- Pero si en NEW.raw_app_meta_data ya viene 'super_admin' (por actualización administrativa), respetarlo
    IF COALESCE(NEW.raw_app_meta_data->>'role', '') != 'super_admin' AND COALESCE(OLD.raw_app_meta_data->>'role', '') != 'super_admin' THEN
      NEW.raw_app_meta_data := NEW.raw_app_meta_data || jsonb_build_object('role', COALESCE(NEW.raw_user_meta_data->>'role', 'store_owner'));
    END IF;
  END IF;
  RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_store_egress(p_store_id text, p_bytes bigint)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
      BEGIN
        UPDATE public.stores
        SET egress_bytes = COALESCE(egress_bytes, 0) + p_bytes
        WHERE id = p_store_id;
      END;
      $function$
;

CREATE OR REPLACE FUNCTION public.increment_views(store_id_param text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE stores
  SET views = COALESCE(views, 0) + 1
  WHERE id = store_id_param;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_whatsapp_clicks(store_id_param text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  UPDATE stores
  SET whatsapp_clicks = COALESCE(whatsapp_clicks, 0) + 1
  WHERE id = store_id_param;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.initialize_store(p_id text, p_slug text, p_name text, p_phone text, p_country_code text, p_plan text, p_owner_id uuid, p_model text, p_niche text, p_category_id text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  -- Insertar tienda
  INSERT INTO public.stores (
    id, slug, name, phone, country_code, plan, owner_id, model, active, is_published
  ) VALUES (
    p_id, p_slug, p_name, p_phone, p_country_code, p_plan, p_owner_id, p_model, true, true
  );

  -- Insertar categoría inicial
  INSERT INTO public.categories (
    id, store_id, name
  ) VALUES (
    p_category_id, p_id, 'General'
  );

  -- Insertar productos de ejemplo
  INSERT INTO public.products (
    id, store_id, category_id, name, price, image, description, is_on_sale, visible, is_sample
  ) VALUES 
  (
    'p_' || substr(md5(random()::text), 1, 8), p_id, p_category_id, 
    'Producto de Ejemplo 1', 49.90, 
    'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80', 
    'Esta es una descripción de ejemplo para tu primer producto. Puedes editarla o eliminarla desde el panel de administración.', 
    false, true, true
  ),
  (
    'p_' || substr(md5(random()::text), 1, 8), p_id, p_category_id, 
    'Producto en Oferta 2', 99.90, 
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80', 
    'Este es un producto de ejemplo con precio de oferta. Puedes configurar precios anteriores para mostrar descuentos.', 
    true, true, true
  ),
  (
    'p_' || substr(md5(random()::text), 1, 8), p_id, p_category_id, 
    'Producto de Ejemplo 3', 29.90, 
    'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80', 
    'Otro producto de muestra para decorar tu catálogo inicial.', 
    false, true, true
  );
END;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_reclamacion(p_tenant_id text, p_consumidor_nombre text, p_consumidor_tipo_doc text, p_consumidor_num_doc text, p_consumidor_domicilio text, p_consumidor_telefono text, p_consumidor_email text, p_es_menor_edad boolean, p_tutor_nombre text, p_tutor_num_doc text, p_bien_descripcion text, p_bien_monto numeric, p_tipo text, p_descripcion text, p_pedido_consumidor text)
 RETURNS TABLE(id uuid, numero_correlativo integer, fecha timestamp with time zone, empresa_nombre text, empresa_ruc text, empresa_direccion text, empresa_url text)
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_next_num      INTEGER;
  v_emp_nombre    TEXT;
  v_emp_ruc       TEXT;
  v_emp_dir       TEXT;
  v_emp_url       TEXT;
  v_id            UUID;
  v_fecha         TIMESTAMPTZ;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext(p_tenant_id));
 
  SELECT COALESCE(MAX(r.numero_correlativo), 0) + 1
    INTO v_next_num
    FROM reclamaciones r
   WHERE r.tenant_id = p_tenant_id;
 
  SELECT
    COALESCE(s.empresa_razon_social, s.name),
    s.empresa_ruc,
    s.empresa_direccion,
    concat('dizi.pe/t/', s.slug)
  INTO v_emp_nombre, v_emp_ruc, v_emp_dir, v_emp_url
  FROM stores s
  WHERE s.id = p_tenant_id;
 
  INSERT INTO reclamaciones (
    tenant_id, numero_correlativo,
    empresa_nombre, empresa_ruc, empresa_direccion, empresa_url,
    consumidor_nombre, consumidor_tipo_doc, consumidor_num_doc,
    consumidor_domicilio, consumidor_telefono, consumidor_email,
    es_menor_edad, tutor_nombre, tutor_num_doc,
    bien_descripcion, bien_monto,
    tipo, descripcion, pedido_consumidor
  ) VALUES (
    p_tenant_id, v_next_num,
    v_emp_nombre, v_emp_ruc, v_emp_dir, v_emp_url,
    p_consumidor_nombre, p_consumidor_tipo_doc, p_consumidor_num_doc,
    p_consumidor_domicilio, p_consumidor_telefono, p_consumidor_email,
    p_es_menor_edad, p_tutor_nombre, p_tutor_num_doc,
    p_bien_descripcion, p_bien_monto,
    p_tipo, p_descripcion, p_pedido_consumidor
  )
  RETURNING reclamaciones.id, reclamaciones.fecha
    INTO v_id, v_fecha;
 
  RETURN QUERY
    SELECT v_id, v_next_num, v_fecha, v_emp_nombre, v_emp_ruc, v_emp_dir, v_emp_url;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.process_referral_reward(p_referred_store_id text, p_referred_plan text, p_referred_price numeric)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  v_referrer_slug TEXT;
  v_referred_slug TEXT;
  v_rewarded BOOLEAN;
  v_referrer_id TEXT;
  v_referrer_plan TEXT;
  v_referrer_expires TIMESTAMPTZ;
BEGIN
  -- 1. Obtener datos de la tienda referida
  SELECT referred_by, referral_rewarded, slug 
  INTO v_referrer_slug, v_rewarded, v_referred_slug
  FROM public.stores 
  WHERE id = p_referred_store_id;

  -- 2. Validaciones de salida temprana
  -- - No tiene referente
  -- - Ya fue premiado antes
  -- - Es una auto-referencia (intento de fraude)
  IF v_referrer_slug IS NULL OR v_referrer_slug = '' OR v_rewarded = TRUE OR v_referrer_slug = v_referred_slug THEN
    RETURN;
  END IF;

  -- 3. Buscar datos de la tienda referente por su slug
  SELECT id, plan, plan_expires_at
  INTO v_referrer_id, v_referrer_plan, v_referrer_expires
  FROM public.stores 
  WHERE slug = v_referrer_slug;

  -- Si el referente no existe, no procesamos nada
  IF v_referrer_id IS NULL THEN
    RETURN;
  END IF;

  -- 4. Procesar recompensa de TIEMPO para el REFERENTE (30 días de suscripción gratis)
  IF v_referrer_plan = 'semilla' THEN
    -- Si el referente estaba en plan Semilla (gratuito), se le hace un upgrade al plan del referido por 30 días
    UPDATE public.stores
    SET 
      plan = p_referred_plan,
      subscription_status = 'active',
      plan_expires_at = NOW() + INTERVAL '30 days',
      plan_duration_months = 1,
      custom_price = NULL
    WHERE id = v_referrer_id;
  ELSE
    -- Si ya tenía un plan de pago, se le extienden 30 días adicionales a su expiración actual
    UPDATE public.stores
    SET plan_expires_at = COALESCE(
      CASE 
        WHEN plan_expires_at < NOW() THEN NOW() 
        ELSE plan_expires_at 
      END,
      NOW()
    ) + INTERVAL '30 days'
    WHERE id = v_referrer_id;
  END IF;

  -- 5. Procesar recompensa de TIEMPO para el REFERIDO (tienda recién activada)
  -- Se le extienden 30 días adicionales a la vigencia del plan que acaba de adquirir
  UPDATE public.stores
  SET plan_expires_at = COALESCE(
    CASE 
      WHEN plan_expires_at < NOW() THEN NOW() 
      ELSE plan_expires_at 
    END,
    NOW()
  ) + INTERVAL '30 days'
  WHERE id = p_referred_store_id;

  -- 6. Marcar la tienda referida como premiada para evitar doble asignación
  UPDATE public.stores 
  SET referral_rewarded = TRUE 
  WHERE id = p_referred_store_id;
  
END;
$function$
;

CREATE OR REPLACE FUNCTION public.set_invite_expires_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  IF NEW.expires_at IS NULL THEN
    -- El invite (el link) expira en 30 días por defecto, independientemente de la duración del plan
    NEW.expires_at := NOW() + INTERVAL '30 days';
  END IF;
  RETURN NEW;
END;
$function$
;

-- Triggers
DROP TRIGGER IF EXISTS trg_invite_expires_at ON public.invites;
CREATE TRIGGER trg_invite_expires_at BEFORE INSERT ON public.invites FOR EACH ROW EXECUTE FUNCTION set_invite_expires_at();

DROP TRIGGER IF EXISTS trg_products_touch_store ON public.products;
CREATE TRIGGER trg_products_touch_store AFTER INSERT ON public.products FOR EACH ROW EXECUTE FUNCTION handle_store_touch_updated_at();

DROP TRIGGER IF EXISTS trg_products_touch_store ON public.products;
CREATE TRIGGER trg_products_touch_store AFTER DELETE ON public.products FOR EACH ROW EXECUTE FUNCTION handle_store_touch_updated_at();

DROP TRIGGER IF EXISTS trg_products_touch_store ON public.products;
CREATE TRIGGER trg_products_touch_store AFTER UPDATE ON public.products FOR EACH ROW EXECUTE FUNCTION handle_store_touch_updated_at();

DROP TRIGGER IF EXISTS trg_stores_touch_updated_at ON public.stores;
CREATE TRIGGER trg_stores_touch_updated_at BEFORE UPDATE ON public.stores FOR EACH ROW EXECUTE FUNCTION handle_store_touch_updated_at();

DROP TRIGGER IF EXISTS trg_user_sync_role ON auth.users;
CREATE TRIGGER trg_user_sync_role
  BEFORE INSERT OR UPDATE ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_user_sync_role();

-- Storage Configuration
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('images', 'images', true, 10485760, null)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Authenticated Delete Access" ON storage.objects;
CREATE POLICY "Authenticated Delete Access" ON storage.objects FOR DELETE TO authenticated USING ((bucket_id = 'images'::text));
DROP POLICY IF EXISTS "Authenticated Insert Access" ON storage.objects;
CREATE POLICY "Authenticated Insert Access" ON storage.objects FOR INSERT TO authenticated WITH CHECK ((bucket_id = 'images'::text));
DROP POLICY IF EXISTS "Authenticated Update Access" ON storage.objects;
CREATE POLICY "Authenticated Update Access" ON storage.objects FOR UPDATE TO authenticated USING ((bucket_id = 'images'::text)) WITH CHECK ((bucket_id = 'images'::text));
DROP POLICY IF EXISTS "Public Insert Access" ON storage.objects;
CREATE POLICY "Public Insert Access" ON storage.objects FOR INSERT TO public WITH CHECK ((bucket_id = 'images'::text));
DROP POLICY IF EXISTS "Public Read Access" ON storage.objects;
CREATE POLICY "Public Read Access" ON storage.objects FOR SELECT TO public USING ((bucket_id = 'images'::text));

-- 9. Table and View Privileges (como estaban antes de la Fase 0)
GRANT ALL ON TABLE public.categories TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.invites TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.products TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.reclamaciones TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.stores TO anon, authenticated, service_role;
GRANT ALL ON TABLE public.v_expiring_subscriptions TO anon, authenticated, service_role;

-- 10. Function Privileges (como estaban antes de la Fase 0)
GRANT EXECUTE ON FUNCTION public.activate_subscription(text, text, integer, text, numeric) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.activate_subscription(text, text, integer, numeric, boolean, timestamp with time zone) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.activate_subscription_with_invite(text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.cancel_subscription(text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_invite(text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.degrade_expired_plans() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.extend_subscription(text, integer) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_public_store(text, integer, integer) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.get_public_store_products(text, integer, integer, text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.handle_store_touch_updated_at() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.handle_user_sync_role() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.increment_store_egress(text, bigint) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.increment_views(text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.increment_whatsapp_clicks(text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.initialize_store(text, text, text, text, text, text, uuid, text, text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.insert_reclamacion(text, text, text, text, text, text, text, boolean, text, text, text, numeric, text, text, text) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.process_referral_reward(text, text, numeric) TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.set_invite_expires_at() TO anon, authenticated, service_role;


